fix status columns in blotter
alor-broker/Astras-Trading-UI pull request #1003
Opened 2023-05-31 13:24 UTC by agushasok

add filters by Suspended status

Fixes #995 

# Description

fix status columns in blotter
add filters by Suspended status

# Testing

see in linked issue

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2023-06-01 03:52 UTC, sbelashevskiy reviewed
*

2023-06-01 03:52 UTC, sbelashevskiy commented on src/assets/i18n/blotter/blotter-common/ru.json
> +    "rejected": "Отложен"
А точно у этого статуса такой смысл? Вообще rejected это не отложен, а отклонен.

2023-06-01 04:08 UTC, sbelashevskiy requested changes
listOfFilter в переводах нужно вынести в общее место

2023-06-01 10:33 UTC, agushasok commented on src/assets/i18n/blotter/blotter-common/ru.json
> +    "rejected": "Отложен"
договорились пока оставить так и не менять на беке

2023-06-02 03:54 UTC, sbelashevskiy requested changes

2023-06-02 03:54 UTC, sbelashevskiy commented on src/assets/i18n/blotter/blotter-common/en.json
> +  "ypeFilters": {
опечатка

2023-06-02 10:03 UTC, sbelashevskiy approved these changes

2023-06-02 10:03 UTC, merged