#1095 fix input number rounding
alor-broker/Astras-Trading-UI pull request #1101
Opened 2023-08-01 11:33 UTC by agushasok

Fixes #1095 

# Description

fix input number rounding

# Testing

see point 2 in issue

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2023-08-01 11:57 UTC, sbelashevskiy requested changes

2023-08-01 11:57 UTC, sbelashevskiy commented on src/app/shared/components/input-number/input-number.component.ts
> +    let newValue = MathHelper.roundPriceByMinStep(currentValue + step, this.step ?? 1);
константа step уже определена в 140 строке, зачем ее дублировать?

2023-08-02 10:22 UTC, agushasok commented on src/app/shared/components/input-number/input-number.component.ts
> +    let newValue = MathHelper.roundPriceByMinStep(currentValue + step, this.step ?? 1);
та константа - это не минимальный шаг. Если minStep=0.5 и пользователь с зажатым shift скроллит, то это переменная будет равна 5. и цена будет округляться до целого, вместо того, чтоб до кратного 0.5

2023-08-02 10:50 UTC, sbelashevskiy requested changes

2023-08-02 10:50 UTC, sbelashevskiy commented on src/app/shared/components/input-number/input-number.component.ts
> +    let newValue = MathHelper.roundPriceByMinStep(currentValue + step, this.step ?? 1);
Значит нужно добавить const valueStep = this.step ?? 1;
const move= valueStep *  multiplier;
...MathHelper.roundPriceByMinStep(currentValue + move, valueStep) чтобы была явно видна разница, а не только автор ее видел.

И название MathHelper.roundPriceByMinStep неудачное. По шагу округляться может не только цена и это компонент не только для цены

2023-08-03 04:21 UTC, sbelashevskiy approved these changes

2023-08-03 04:21 UTC, merged