Dm dev/1105
alor-broker/Astras-Trading-UI pull request #1117
Opened 2023-08-08 13:11 UTC by agushasok

Fixes #1105 

# Description

add price difference in percents on price input field

# Testing

open order submit widget/modal
select instrument that positions contain
enter value in price field

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2023-08-09 03:48 UTC, sbelashevskiy requested changes

2023-08-09 03:48 UTC, sbelashevskiy commented on src/app/shared/components/input-number/input-number.component.ts
не универсальное решение. Зачем передавать 3 интпута, тем более строковые, если можно передать TemplateRef.

2023-08-09 11:05 UTC, sbelashevskiy requested changes

2023-08-09 11:05 UTC, sbelashevskiy commented on src/app/shared/components/input-number/input-number.component.ts
> +  suffix?: string | TemplateRef<any> | null;
Я не вижу ни одного кейса использования строки в качестве суффикса. Зачем она здесь?

2023-08-09 11:38 UTC, agushasok commented on src/app/shared/components/input-number/input-number.component.ts
> +  suffix?: string | TemplateRef<any> | null;
на будущее. Компонент общий, может потом понадобится что-то ещё отображать в других полях

2023-08-10 04:03 UTC, sbelashevskiy approved these changes

2023-08-10 04:03 UTC, merged