#950 change app release design
alor-broker/Astras-Trading-UI pull request #1128
Opened 2023-08-16 13:23 UTC by agushasok

Fixes #950  

# Description

change app release design

# Testing

see in linked issue

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2023-08-17 10:33 UTC, PilgrimViis requested changes
1. Переделать текст о котором договорились
2. Убрать кнопку ОК
3. Сделать закрытие по крестику или снаружи. 
4. Сделать чтобы отмечалось прочитанным сразу.

2023-08-23 05:44 UTC, PilgrimViis approved these changes

2023-08-28 04:17 UTC, sbelashevskiy requested changes
Панель смещена относительно остального текста 
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/47d1f560-1021-4690-8018-cc6fcb5959aa)

2023-08-28 04:17 UTC, sbelashevskiy commented on src/app/modules/application-meta/widgets/application-updated-widget/application-updated-widget.component.ts
> +  isProblemCollapseActiveChange(isActive: boolean) {
метод не используется

2023-08-28 04:17 UTC, sbelashevskiy commented on src/app/modules/application-meta/widgets/application-updated-widget/application-updated-widget.component.ts
метод getLinkToRelease больше не используется

2023-08-28 08:06 UTC, sbelashevskiy approved these changes

2023-08-28 08:06 UTC, merged