Dm dev/1127
alor-broker/Astras-Trading-UI pull request #1129
Opened 2023-08-21 14:10 UTC by agushasok

Fixes #1127 

# Description

create base table component for blotter tables

# Testing

see in linked issue

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2023-08-24 07:12 UTC, agushasok commented on src/app/modules/blotter/components/base-table/base-table.component.ts
> +      setTimeout(()=> this.scrollHeight$.next(x));
написать Сергею,ьпочему сет таймаут

2023-08-24 07:16 UTC, agushasok commented on src/app/modules/blotter/components/orders/orders.component.ts
>    recalculateTableWidth(widthChange: { columnWidth: number, delta: number | null }) {
почему не удалено

2023-08-24 07:19 UTC, agushasok commented on src/app/modules/blotter/components/positions/positions.component.ts
> +  settings$!: Observable<BlotterSettings>;
удалить

2023-08-24 07:19 UTC, agushasok commented on src/app/modules/blotter/components/positions/positions.component.ts
> +  isFilterDisabled = () => Object.keys(this.filter$.getValue()).length === 0;
удалить

2023-08-24 07:21 UTC, agushasok commented on src/app/modules/blotter/components/repo-trades/repo-trades.component.ts
> +  settings$!: Observable<BlotterSettings>;
удалить

2023-08-24 07:28 UTC, agushasok commented on src/app/modules/blotter/components/base-table/base-table.component.ts
> +  protected translateStatus(status: string) {
Попробовать использовать transloco

2023-08-24 07:30 UTC, agushasok commented on src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
>    formatDate(date: Date) {
вынести эту логику в общий компонент

2023-08-24 07:31 UTC, agushasok commented on src/app/modules/blotter/components/trades/trades.component.ts
> +  settings$!: Observable<BlotterSettings>;
удалить

2023-08-24 07:34 UTC, PilgrimViis approved these changes
Одобрил, но пожалуйста исправь все то о чем обсуждали.

2023-08-28 04:38 UTC, sbelashevskiy requested changes

2023-08-28 04:38 UTC, sbelashevskiy commented on src/app/modules/blotter/components/base-table/base-table.component.ts
> +    this.scrollHeight$.complete();
комплитить нужно все используемые BehaviourSubject

2023-08-28 04:38 UTC, sbelashevskiy commented on src/app/modules/blotter/components/orders/orders.component.ts
> +  fileSuffix = 'Заявки';
Захаркожено и не локализовано

2023-08-28 04:38 UTC, sbelashevskiy commented on src/app/modules/blotter/components/base-table/base-table.component.ts
> +  protected fileSuffix!: string;
Для части таблиц это поле вообще не определено, при этом здесь утверждается, что у него всегда есть значение
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/86d5b6c9-beeb-43d7-896b-a58577df9d48)

2023-08-28 09:40 UTC, sbelashevskiy requested changes

2023-08-28 10:42 UTC, sbelashevskiy requested changes

2023-08-28 10:42 UTC, sbelashevskiy commented on src/app/modules/blotter/components/base-table/base-table.component.ts
> +        tap(({ tBlotterCommon }) => {
да блин ЗАЧЕМ тут вообще tap и зачем выносить valueTranslators вне стрима, если она используется тобько внутри него?

2023-08-28 10:54 UTC, agushasok commented on src/app/modules/blotter/components/base-table/base-table.component.ts
> +        tap(({ tBlotterCommon }) => {
ты в прошлом коммнете написал, что это нечитаемый метод и что нужно вынести 3 стрима в отдельные переменные, а теперь пишешь, зачем я это сделал

2023-08-28 11:13 UTC, sbelashevskiy approved these changes

2023-08-28 11:13 UTC, merged