Github docs
alor-broker/Astras-Trading-UI pull request #1163
Opened 2023-09-08 19:23 UTC by PilgrimViis

Fixes #1162  

# Description

Added a link to navbar,
Added a panel with a link for every help-entry
Using v2 API to get responces directly from github

# Testing & Risk
Nothing specific

# Do you agree with those?
- [x] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [x] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2023-09-11 09:33 UTC, sbelashevskiy requested changes
1. На мой взгляд отступа не хватает
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/1fa84343-07fc-4ac4-a22c-3e9ab8d32355)
2. Окно справки очень широкое. Как то ссылка справа теряется. Может лучше ссылку во второй строке показывать?
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/b063185c-8534-4a30-8206-1f06c61c9b30)

2023-09-11 09:33 UTC, sbelashevskiy commented on src/app/modules/help/components/help/help.component.html
Лучше обернуть все в \<ng-container\> и получить ссылку на директиву transloco в ней:
`<ng-container *transloco="let t;">
...остальной код
</ng-container>`

Не критично,  конечно: у директивы есть оптимизация и она инстанцируется 1 раз, но если понадобится сменить путь к файлу перевода, то это нужно будет сделать в 1 месте.
По такому принципу эта директива используется в других компонентах

2023-09-11 09:33 UTC, sbelashevskiy commented on src/app/modules/help/components/help/help.component.html
> +    [nzAction]="docsLink">
Ресурс справки предоставляет навигацию к конкретной странице компонента, для которого было открыто данное окно, например https://alor.gitbook.io/astras/**order-submit**
Может стоит открывать конкретную страницу?

2023-09-12 05:42 UTC, sbelashevskiy commented
Кстати, еще у двух виджетов справки не хватает
https://github.com/alor-broker/Astras-Trading-UI/issues/980

2023-09-12 07:28 UTC, PilgrimViis commented on src/app/modules/help/components/help/help.component.html
> +    [nzAction]="docsLink">
Обсудили на дейлике. Обсужу с РГ, чтобы понять нужна ли нам справка внутри Астраса или нет.

2023-09-12 07:30 UTC, PilgrimViis commented on src/app/modules/help/components/help/help.component.html
Готово

2023-09-12 08:04 UTC, sbelashevskiy approved these changes

2023-09-12 08:04 UTC, merged