Dm dev/1289
alor-broker/Astras-Trading-UI pull request #1340
Opened 2023-11-23 15:47 UTC by agushasok

Fixes #1289 

# Description

add new rules in linter

# Testing

run yarn lint comand

# Risk

all errors of linter was fixed

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2023-11-24 08:29 UTC, sbelashevskiy requested changes

2023-11-24 08:29 UTC, sbelashevskiy commented on src/app/modules/order-commands/components/order-forms/edit-limit-order-form/edit-limit-order-form.component.ts
> +    ).subscribe((x: { currentOrder: Order, currentInstrument: Instrument }) => {
Зачем здесь указание типа если он выводится?

2023-11-24 08:29 UTC, sbelashevskiy commented on src/app/modules/order-commands/components/order-forms/edit-stop-order-form/edit-stop-order-form.component.ts
> +    ).subscribe((x: { currentOrder: StopOrder, currentInstrument: Instrument }) => {
Указание типа не нужно. Он выводится

2023-11-24 08:29 UTC, sbelashevskiy commented on src/app/modules/order-commands/components/order-forms/limit-order-form/limit-order-form.component.ts
Во всех случаях нужна проверка на null, не проверка на 0.  Проверка на null и проверка на 0 не эквивалентны. Есть инструменты, которые торгуются по отрицательной цене и 0 может быть допустимым значением

2023-11-24 08:29 UTC, sbelashevskiy commented on src/app/modules/orderbook/components/orderbook/orderbook.component.ts
> +        if (!(bestBid ?? 0) || !(bestAsk ?? 0)) {
null/undefinded. 0 допустимое значение

2023-11-24 08:29 UTC, sbelashevskiy commented on src/app/modules/scalper-order-book/components/scalper-order-book-body/scalper-order-book-body.component.ts
> +          enabled: (x.enableAutoAlign ?? true) && !!(x.autoAlignIntervalSec ?? 0) && x.autoAlignIntervalSec! > 0,
Максимально нечитабельно. 
К тому же лишнее условие.
Тоже самое:  enabled: (x.enableAutoAlign ?? true) && (x.autoAlignIntervalSec ?? 0)  > 0

2023-11-24 08:29 UTC, sbelashevskiy commented on src/app/modules/scalper-order-book/components/table-ruler/table-ruler.component.ts
> +        leftSpace > +markerBounds.width + 5
зачем? Где тут строки, чтобы применять этот оператор?

2023-11-24 11:09 UTC, agushasok commented on src/app/modules/dashboard/services/onboarding.service.ts
> +  protected isCompleted = false;
потому что линтер ругается, что свойство не readonly, а компилятор - что свойству присваивается новое значение (в конструкторе), если поставить readonly

2023-11-24 11:28 UTC, agushasok commented on src/app/modules/feedback/widgets/feedback-widget/feedback-widget.component.ts
> +      if (this.askComment as boolean) {
потому что свойство уже проверялось на правдивость в условии и линтер думает, что в нём в лежит false, не смотря на то, что оно меняется в вызываемом методе

2023-11-24 11:44 UTC, sbelashevskiy commented on src/app/modules/dashboard/services/onboarding.service.ts
> +  protected isCompleted = false;
да а модификатор доступа то тут причем? Задача почистить код, не не подключить новые правила и зашлушить их

2023-11-24 11:51 UTC, sbelashevskiy commented on src/app/modules/dashboard/services/onboarding.service.ts
> +  protected isCompleted = false;
Кроме того, это поле вообще не нужно - оно читается 1 раз в методе start и больше никогда не меняется. Точно также его можно вообще удалить и в start вызвать getIsCompleted()

2023-11-24 12:02 UTC, sbelashevskiy commented on src/app/modules/feedback/widgets/feedback-widget/feedback-widget.component.ts
> +      if (this.askComment as boolean) {
Значит это правило нужно убрать т.к. работает оно криво. Не нужно уродовать код ради таких правил

2023-12-11 07:15 UTC, sbelashevskiy requested changes
1. Такого приведения через обертки быть не должно. Здесь явно нужна просто проверка на null
![1](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/5865dc14-20c3-449e-a244-c5a5ab24c8a8)

2. Где нужна проверка на null, дожна быть проверак именно на null. Никаких пустых строк быть не должно 
![2](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/8d02df40-d0c2-48d0-bdcc-aff25ffc1f14)

3. ![3](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/e48125d9-33d9-4a05-a6bd-f65655dcab1d)
Здесь нужна нормальная модель. Сторонний сервис здесь вообще возвращает any и при таком подходе мы даже не сможет узнать что из возвращаемого значения используется у нас в коде

4. Такие места говорят о проблемах с моделями
![5](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/338b99d5-bac9-47aa-9a26-4a37a4ce2e1e)
Нужно пересматривать модели, а не прятать ошибка eslint

5. ![9](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/de62d35b-d648-432c-a419-9b350b9d0dd5)
тут была проверка именно на null, зачем тут эта замена?

2023-12-13 12:44 UTC, sbelashevskiy approved these changes

2023-12-13 12:44 UTC, merged