Dm dev 1311
alor-broker/Astras-Trading-UI pull request #1399
Opened 2023-12-14 15:47 UTC by agushasok

Fixes #1311 

# Description

fix tooltip aperance in treemap

# Testing

see in linked issue

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2023-12-15 04:16 UTC, sbelashevskiy requested changes
Тултип показывается через раз

https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/bce899dc-716c-4d7e-b8b9-3050386f82dd

2023-12-18 11:11 UTC, sbelashevskiy requested changes
Теперь тултип невозможно убрать

Uploading g50pZF1A8f.mp4…

2023-12-18 14:32 UTC, agushasok commented
> Теперь тултип невозможно убрать
> 
>  g50pZF1A8f.mp4

сорри, не допроверил, исправил

2023-12-19 04:10 UTC, sbelashevskiy approved these changes

2023-12-19 04:10 UTC, merged