Fix #138
alor-broker/Astras-Trading-UI pull request #146
Opened 2022-05-06 11:45 UTC by exvion

Fixes Issue #138  

# Description
Исправляет баг описанный в #138 

# Testing
Зайти в настройки стакана и попробовать написать тикер меньше 4 символов.

# Risk
Без серьезных изменений

# Do you agree with those?
- [x] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [x] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2022-05-11 06:16 UTC, PilgrimViis requested changes

2022-05-11 06:16 UTC, PilgrimViis commented on src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.ts
> +            Validators.minLength(2)
Надо сделать 1, а не 2.

2022-05-11 06:17 UTC, PilgrimViis commented
@sbelashevskiy  Заполни пожалуйста форму пул реквеста.

2022-05-11 07:07 UTC, PilgrimViis commented
@exvion большое спасибо за фикс. Заполните пожалуйста только форму пул-реквеста, хотя бы в 1-2 слова по каждому пункту. Можно на русском.

2022-05-12 06:46 UTC, PilgrimViis approved these changes

2022-05-12 06:48 UTC, merged

2022-05-12 06:48 UTC, PilgrimViis commented
@exvion я поправил описание пул-реквеста для вас, чтобы вы видели на примере как это делается. Но большая просьба, заполнять эти поля на будущее, они правда нужны. Спасибо за ваш фикс.

2022-05-12 07:46 UTC, sbelashevskiy reviewed
Reviewed, OK

2022-05-12 09:56 UTC, exvion commented
@PilgrimViis спасибо за пример)

2022-05-30 15:37 UTC, PilgrimViis commented
@exvion можете, пожалуйста, написать Аvatars08 в телеграм? Не пожалеете =)