#1594 add scalper orderbook stop orders moving
alor-broker/Astras-Trading-UI pull request #1603
Opened 2024-04-11 12:01 UTC by agushasok

Fixes #1594 

# Description

add scalper orderbook stop orders moving

# Testing

add scalper orderbook widget
try replace stop order

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2024-04-12 07:55 UTC, agushasok commented on src/app/modules/scalper-order-book/models/scalper-order-book.model.ts
> +  price?: number;
переименовать в price и triggerPrice

2024-04-12 07:56 UTC, agushasok commented on src/app/modules/scalper-order-book/services/scalper-orders.service.ts
> +                price: order.price! - (order.linkedPrice - updates.price),
добавить округление

2024-04-16 10:35 UTC, PilgrimViis requested changes

2024-04-16 10:35 UTC, PilgrimViis commented on src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.ts
> +        const minOrderPrice = Math.min(...currentOrders.map(x => x.triggerPrice ?? x.price!));
Пожалуйста убери ! и поставь ?? throw new Error("Price or trigger price should be present")

2024-04-16 10:35 UTC, PilgrimViis commented on src/app/modules/scalper-order-book/components/scalper-order-book-body/scalper-order-book-body.component.ts
> +          down: !!(downPrice ?? 0) && !!currentOrders.find(o => (o.triggerPrice ?? o.price!) < downPrice!),
Пожалуйста убери ! и поставь ?? throw new Error("Price or trigger price should be present")

2024-04-16 11:26 UTC, closed without merging