Dm dev/1648
alor-broker/Astras-Trading-UI pull request #1668
Opened 2024-05-07 14:42 UTC by agushasok

Fixes #1648 

# Description

add new fields to bonds screener widget, fix problems

# Testing

see in linked issue

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2024-05-08 07:15 UTC, agushasok commented on src/app/modules/bond-screener/components/bond-screener/bond-screener.component.ts
> +                        closestCoupon: (JSON.parse(JSON.stringify(edge.node.coupons ?? [])) as BondCoupon[])
использовать спред-оператор

2024-05-08 07:18 UTC, agushasok commented on src/app/modules/bond-screener/components/bond-screener/bond-screener.component.ts
> +                          .find((node: BondCoupon) => new Date(node.date!).getTime() > new Date().getTime()),
убрать проверку на  null

2024-05-08 07:22 UTC, agushasok commented on src/app/modules/bond-screener/models/bond-screener.model.ts
> +  date?: Date;
сделать обязательным

2024-05-08 07:23 UTC, agushasok commented on src/app/modules/bond-screener/services/bond-screener.service.ts
> +    const filtersCopy = JSON.parse(JSON.stringify(filters)) as DefaultTableFilters;
убрать

2024-05-08 07:33 UTC, agushasok commented on src/app/modules/bond-screener/services/bond-screener.service.ts
> +      const [fromDay, fromMonth, fromYear] = ((filters.couponDateFrom ?? '') as string).split('.').map(d => +d);
(filters.couponDateFrom as string | undefined ?? '')

2024-05-08 07:33 UTC, agushasok commented on src/app/modules/bond-screener/services/bond-screener.service.ts
> +      const [toDay, toMonth, toYear] = ((filters.couponDateTo ?? '') as string).split('.').map(d => +d);
см. выше

2024-05-08 07:37 UTC, agushasok commented on src/app/modules/bond-screener/services/bond-screener.service.ts
> +      someFilters.push({ intervalInDays: { gte: +filters.couponIntervalInDaysFrom } });
сделать приведение через Number(...)

2024-05-08 07:41 UTC, agushasok commented on src/app/shared/components/infinite-scroll-table/infinite-scroll-table.component.less
> +  .warning-msg {
Убрать

2024-05-21 05:00 UTC, sbelashevskiy requested changes

2024-05-21 05:30 UTC, sbelashevskiy requested changes

2024-05-21 05:30 UTC, sbelashevskiy commented on src/app/modules/bond-screener/services/bond-screener.gql-schemas.ts
> +  const GetBondScreenerBasicInformationSchema = getPartialSchema<BasicInformation>(BasicInformationSchema(), ['key', 'exchange']);
BasicInformationSchema вообще не содержит поля key

2024-05-22 06:14 UTC, sbelashevskiy commented on src/app/shared/utils/graph-ql-helper.ts
> +  private static zodKeys(schema: ZodTypeAny): string[] {
ну дак нужно просто по аналогии сделалть ообработку этих случаев

2024-05-22 06:28 UTC, sbelashevskiy requested changes

2024-05-22 06:28 UTC, sbelashevskiy commented on src/app/shared/utils/graph-ql-helper.ts
> +    // make sure schema is not null or undefined
бессмысленные комментарии

2024-05-22 06:28 UTC, sbelashevskiy commented on src/app/modules/bond-screener/services/bond-screener.service.ts
> +      (filters.offerDateFrom as string | null) ?? null,
еще хуже чем было. Вообще бессмыслица какая-то
Что вообще этот код делает  (filters.offerDateFrom as string | null) ?? null

filters.offerDateFrom  может быть строкой или null. Если он null, то взять дефолтное null?
Что это? Зачем?

2024-05-22 08:27 UTC, agushasok commented on src/app/shared/utils/graph-ql-helper.ts
> +  private static zodKeys(schema: ZodTypeAny): string[] {
в схемах фильтров почти всё через lazy определяется и зацикливания есть, так как в фильтрах есть поля and, и or, в которых та же схема, внутри которой они определены

2024-05-23 05:51 UTC, sbelashevskiy approved these changes

2024-05-23 06:59 UTC, merged