#1705 fix validation errors display
alor-broker/Astras-Trading-UI pull request #1708
Opened 2024-06-05 07:32 UTC by agushasok

Fixes #1705 

# Description

fix validation errors display

# Testing

see in linked issue

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2024-06-05 07:58 UTC, sbelashevskiy requested changes

2024-06-05 07:58 UTC, sbelashevskiy commented on src/app/modules/terminal-settings/components/hot-key-input/hot-key-input.component.html
> +    <span
Эта ошибка "приляпана" вне стандартного контейнера для ошибок и вообще выглядит как не часть этого контрола. Возникает логичный вопрос - зачем она здесь?

2024-06-05 07:58 UTC, sbelashevskiy commented on src/app/modules/terminal-settings/components/hot-key-settings-form/hot-key-settings-form.component.html
> -      <ats-hot-key-input actionName="cancelOrdersAll" formControlName="cancelOrdersAll"></ats-hot-key-input>
Может уже стоит завести соотвествующие массивы для общих команд, для специфичных и итерируясьясь по ним сделать отрисовку вместо постоянного размножения этого списка контролов

2024-06-05 09:19 UTC, agushasok commented on src/app/modules/terminal-settings/components/hot-key-input/hot-key-input.component.html
> +    <span
потому что контейнер с ошибками отображается только в случае, когда в контроле есть errors. А в данном случае Ошибок валидации в контроле этого поля нет, т.к. валидация висит в родительском компоненте

2024-06-06 07:15 UTC, agushasok commented on src/app/modules/terminal-settings/components/hot-key-settings-form/hot-key-settings-form.component.html
> +      [isNotUniqueError]="form.controls[keyType]!.hasError('notUnique')"
Отрисовать ошибку уникальности снаружи

2024-06-06 07:15 UTC, agushasok commented on src/app/modules/terminal-settings/components/hot-key-settings-form/hot-key-settings-form.component.html
> +      [isNotUniqueError]="form.controls[keyType]!.hasError('notUnique')"
Отрисовать ошибку уникальности снаружи

2024-06-06 07:18 UTC, PilgrimViis approved these changes

2024-06-07 05:17 UTC, sbelashevskiy approved these changes

2024-06-07 05:17 UTC, merged