fix command modal styles
alor-broker/Astras-Trading-UI pull request #232
Opened 2022-06-14 13:26 UTC by agushasok

Fixes #214 

# Description

# Testing

# Risk

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2022-06-15 05:48 UTC, sbelashevskiy commented on src/app/modules/command/components/command-header/command-header.component.less
> +  flex-wrap: nowrap;
Убивает мобилки

2022-06-15 05:48 UTC, sbelashevskiy commented on src/app/modules/command/components/command-header/command-header.component.less
> +  flex-wrap: nowrap;
Убивает мобилки

2022-06-15 05:52 UTC, sbelashevskiy requested changes
Фикс ломает отображение на мобилках

2022-06-22 14:15 UTC, PilgrimViis commented
Я пока закрою. Когда вернемся к задаче, тогда новый откроем.

2022-06-22 14:15 UTC, closed without merging