Moved widget settings to ngrx store
alor-broker/Astras-Trading-UI pull request #288
Opened 2022-06-28 12:31 UTC by sbelashevskiy

Fixes #197 

# Description

- Добавление/обновление/сохранение настроек вынесено в store
- Синхронизация настроек также реализована в виде store effects. Теперь нет необходимости делать это в сервисе
- Чтение/обновление настроек удалено из сервисов, в том числе из DashboardService. Данные операции теперь производятся через WidgetSettingsService (уже был, но нигде не использовался)

# Testing

Добавление/удаление виджетов
Очистка дашборда
Привязка/отвязка виджета от активного инструмента/портфеля
Обновление настроек виджета

# Risk

Произведены изменения core. При ревью нужно еще раз запустить приложение и повторить шаги тестирования

# Do you agree with those?
- [x] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [x] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2022-06-28 16:57 UTC, PilgrimViis commented
Cannot find module '@ngrx/entity/src/models' or its corresponding type declarations.

13 import { Update } from "@ngrx/entity/src/models"; 

У меня сборка не проходит. Ты точно всё запушил?

2022-06-29 04:21 UTC, sbelashevskiy commented
> Cannot find module '@ngrx/entity/src/models' or its corresponding type declarations.
> 
> 13 import { Update } from "@ngrx/entity/src/models";
> 
> У меня сборка не проходит. Ты точно всё запушил?

Да, все запушено.
Не забудь вызвать **yarn install** - я добавил новый пакет ngrx для работы с коллекциями. И вообще немного версию ngrx поднял

2022-06-30 06:55 UTC, PilgrimViis requested changes

2022-06-30 06:55 UTC, PilgrimViis commented on src/app/shared/services/widget-settings.service.ts
>  export class WidgetSettingsService {
Ты решил его оставить, чтобы создать меньше проблем с совместимостью или чтобы изолировать функционал по получению настроек и не тащить потом Store с селекторами повсюду?

2022-06-30 06:55 UTC, PilgrimViis commented on src/app/modules/dashboard/components/parent-widget/parent-widget.component.ts
> +    // TODO: need to calculate this value. Now it depends on styles
Надо бы убрать TODO. Если считаешь, что это важно, то может создать задачу? Или просто оставить как комментарий, что зависит от стилей и т.д.

2022-06-30 06:55 UTC, PilgrimViis commented on src/app/shared/services/base.service.ts
> -export class BaseService<T extends AnySettings> {
Слушай, а может не стоило его удалять? Могли бы оставить метод GetSettings тут и во всех сервисах можно было бы уменьшить количество кода и зависимостей.

2022-06-30 06:55 UTC, PilgrimViis commented on src/app/modules/instruments/services/instruments.service.ts
> +    // TODO: this method is called from several widgets with the same parameters.
Надо бы убрать TODO. Если это важно, то можно создать рефактор задачу. А если не очень, то просто оставить как поясняющий комментарий.

2022-06-30 06:55 UTC, PilgrimViis commented on src/app/shared/models/instruments/instrument.model.ts
>  export class InstrumentIsinEqualityComparer {
Слушай, вот тут я не уверен, но мне кажется что тут баг. Сейчас этот компаратор не используется нигде. До этого он в 3 местах использовался. Честно говоря, не помню зачем была проверка на ISIN, но хорошо бы проверить этот момент и если он не нужен, то просто удалить весь комперер.

2022-06-30 07:10 UTC, sbelashevskiy commented on package.json
> +    "@ngrx/store": "^13.2.0",
Да у ngrx и angular версии 1:1 идут. Но yarn при инсталляции не жалуется. Обновление angular, скорее всего, потянет обновление других зависимостей, могут возникнуть проблемы.
Надо бы обновиться до angular 14, но ng-zorro пока его не поддерживает.
Думаю, стоит подожать, когда ng-zorro обновят и потом уже занять поднятием версии пакетов

2022-06-30 07:16 UTC, sbelashevskiy commented on src/app/shared/services/widget-settings.service.ts
>  export class WidgetSettingsService {
Да, как минимум есть очень распространненый pipe на проверку, что сеттинг установлен:
filter((s): s is T => !!s)
он практически везде встречался. Возможно, со времени еще что-то такое понадобится.
Настройки используются практически везде, поэтому спрятать подобную логику в этот сервис, я думаю, було целесообразно - если понадобятся какие-то изменения, дополнения, то их проще будет сделать в этом сервисе, чем изменять все обращения к стору

2022-06-30 07:39 UTC, sbelashevskiy commented on src/app/shared/models/instruments/instrument.model.ts
>  export class InstrumentIsinEqualityComparer {
Он использовался в двух местах 
![image](https://user-images.githubusercontent.com/29191749/176619847-dcddffb6-0eaf-4678-891c-722cd4533b1a.png)
причем в AllTradesService использован скорее по аналогии.
Самое странное, что во всех остальных местах, в том числе при выставлении заявки проверки ISIN не было.

По идее если это важно, то такая проверка должна быть везде

2022-06-30 07:47 UTC, PilgrimViis commented on src/app/shared/models/instruments/instrument.model.ts
>  export class InstrumentIsinEqualityComparer {
Мне кажется что API InfoService требовало в каких-то местах ISIN, а в каких-то тикер. Может из-за этого такая логика была нужна.

2022-06-30 11:23 UTC, sbelashevskiy commented on src/app/modules/dashboard/components/parent-widget/parent-widget.component.ts
> +    // TODO: need to calculate this value. Now it depends on styles
Убрал TODO,оставил коммент

2022-06-30 11:23 UTC, sbelashevskiy commented on src/app/modules/instruments/services/instruments.service.ts
> +    // TODO: this method is called from several widgets with the same parameters.
Создал issue https://github.com/alor-broker/Astras-Trading-UI/issues/297

2022-06-30 11:25 UTC, sbelashevskiy commented on src/app/shared/models/instruments/instrument.model.ts
>  export class InstrumentIsinEqualityComparer {
Поправил логику. Судя по API Info требует ISIN. 
Судя по определению ISIN его следует впервую очередь проверять - поправил comparer, теперь для всех виджетов будет одна логика

2022-07-01 05:47 UTC, sbelashevskiy commented on src/app/shared/models/instruments/instrument.model.ts
>  export class InstrumentIsinEqualityComparer {
Судя по использованиб API нужно просто проверять сочетание всех 4 пропертей.
Поправил, добавил тесты https://github.com/alor-broker/Astras-Trading-UI/pull/288/commits/7477e413c87996bb4d52439c4babb7771725884f

2022-07-04 05:41 UTC, merged