Sb master/400
alor-broker/Astras-Trading-UI pull request #401
Opened 2022-08-16 09:55 UTC by sbelashevskiy

Fixes #400 

# Description

Added script to run linter

# Testing

# Risk

No major changes

# Do you agree with those?
- [x] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [x] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2022-08-17 06:13 UTC, PilgrimViis requested changes

2022-08-17 06:13 UTC, PilgrimViis commented on .github/workflows/run_lint.yml
> +  push:
Не уверен что до конца понимаю. Но это лучше делать на коммите, а не на пуше. Есть такая штука husky она может помочь.

2022-08-17 08:13 UTC, sbelashevskiy commented on .github/workflows/run_lint.yml
> +  push:
а зачем запускать джобу на каждый коммит?
я сделал этот скрипт по аналогии с npm_test.yml, который запускает тесты. Сейчас этот скрипт запускается параллельно с тестами. Он запускается исключительно на github и локально ничего не делает.

2022-08-17 08:22 UTC, PilgrimViis commented on .github/workflows/run_lint.yml
> +  push:
Чтобы человек поправил проблемы на ранней стадии, а не когда уже ушло на гитхаб.

2022-08-17 08:32 UTC, sbelashevskiy commented on .github/workflows/run_lint.yml
> +  push:
ну цель конкретно этих изменений - запуск проверки на CD, также, как запускаются тесты, чтобы на ревью пулреквестов было видно проходят чеки или нет
Запуск линтера на каждый коммит локально принудительно может раздражать

2022-08-18 07:06 UTC, PilgrimViis commented on .github/workflows/run_lint.yml
> +  push:
Коммиты делаются очень редко. Но ты прав в том, что на гитхабе это сделать тоже неплохо. Мерджу

2022-08-18 07:06 UTC, merged