Dm dev/390
alor-broker/Astras-Trading-UI pull request #406
Opened 2022-08-17 12:32 UTC by agushasok

Fixes #390 

# Description

add instrument selecting in all instruments table

# Testing

open all instruments widget
click on row table

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2022-08-18 05:14 UTC, sbelashevskiy requested changes

2022-08-18 05:14 UTC, sbelashevskiy commented on src/app/modules/all-instruments/components/all-instruments/all-instruments.component.spec.ts
> +        StoreModule.forRoot({})
для этого есть sharedModuleImportForTests

2022-08-18 07:09 UTC, PilgrimViis approved these changes

2022-08-22 05:39 UTC, PilgrimViis approved these changes

2022-08-22 05:40 UTC, PilgrimViis commented
Вижу что замечание исправлено. Мерджу.

2022-08-22 05:40 UTC, merged