add digits separation
alor-broker/Astras-Trading-UI pull request #492
Opened 2022-09-27 10:31 UTC by agushasok

Fixes #479 

# Description

add digits separation in blotter

# Testing

add blotter widget
select orders/stop-orders/positions/trades tab
look at the columns with numbers

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2022-09-28 04:11 UTC, sbelashevskiy requested changes

2022-09-28 04:11 UTC, sbelashevskiy commented on src/app/modules/blotter/components/positions/positions.component.html
> +        <td *ngIf='shouldShow("volume")'>{{ ord.volume | number : '0.0-4' : 'ru-RU' }}</td>
Почему только для этого поля используются дополнителоьные настройки pipe? Что в нем такого особенного и почему для других они не нужны?

2022-09-28 09:41 UTC, agushasok commented on src/app/modules/blotter/components/positions/positions.component.html
> +        <td *ngIf='shouldShow("volume")'>{{ ord.volume | number : '0.0-4' : 'ru-RU' }}</td>
смотрел отображение для разных локалей, забыл убрать

2022-09-29 03:42 UTC, sbelashevskiy approved these changes
Reviewed, OK

2022-09-29 03:42 UTC, merged