Dm dev/285
alor-broker/Astras-Trading-UI pull request #633
Opened 2022-11-08 10:04 UTC by agushasok

Fixes #285 

# Description

add filters to all trades filters

# Testing

add all trades widget
try filters in table

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2022-11-08 11:45 UTC, sbelashevskiy requested changes
Прогрузка отрабатывает даже если явно были прогружены все записи, удовлетворяющие фильтру

https://user-images.githubusercontent.com/29191749/200555356-f1ac2853-7de3-4019-8c7a-41ce08ecfe70.mp4

2022-11-08 11:45 UTC, sbelashevskiy commented on src/app/modules/all-trades/components/all-trades/all-trades.component.ts
> +    this.newTradesSubscription?.unsubscribe();
нужно вызвать complete у всех BehaviorSubject

2022-11-08 11:45 UTC, sbelashevskiy commented on src/app/modules/all-trades/components/all-trades/all-trades.component.ts
> +        if (this.isScrolled) {
Разве this.isScrolled нельзя заменить на s.filters.offset > 0?

2022-11-10 04:34 UTC, sbelashevskiy requested changes

2022-11-10 04:34 UTC, sbelashevskiy commented on src/app/modules/all-trades/components/all-trades/all-trades.component.ts
> +    this.tradesList$.unsubscribe();
нужен complete, а не unsubscribe. Так, как это делается у this.destroy

2022-11-10 04:34 UTC, sbelashevskiy commented on src/app/modules/all-trades/components/all-trades/all-trades.component.ts
> +        if ((s.filters.offset || 0) > 0) {
если можно использовать s.filters.offset > 0, то зачем тогда вообще промежуточная переменная isScrolled?

2022-11-10 11:17 UTC, agushasok commented on src/app/modules/all-trades/components/all-trades/all-trades.component.ts
> +        if ((s.filters.offset || 0) > 0) {
isScrolled для того, чтоб не было постоянной подгрузки при скролле, когда список закончился

2022-11-10 11:37 UTC, sbelashevskiy commented on src/app/modules/all-trades/components/all-trades/all-trades.component.ts
> +        if ((s.filters.offset || 0) > 0) {
дак это можно сделать условием s.res.length < take - кол-во результатов меньше, чем мы запрашивали

2022-11-10 11:41 UTC, agushasok commented on src/app/modules/all-trades/components/all-trades/all-trades.component.ts
> +        if ((s.filters.offset || 0) > 0) {
но запрос-то в следующий раз будет отправляться всё равно, нужно, в любом случае, хранить в переменной, что мы долистали до конца. Или я не так понял?

2022-11-10 11:48 UTC, sbelashevskiy commented on src/app/modules/all-trades/components/all-trades/all-trades.component.ts
> +        if ((s.filters.offset || 0) > 0) {
нет - обновления фильтров нет, а значит и запрос не отправится

2022-11-10 12:44 UTC, sbelashevskiy approved these changes

2022-11-10 12:45 UTC, merged