add keyboard arrows value changing
alor-broker/Astras-Trading-UI pull request #723
Opened 2022-12-06 12:06 UTC by agushasok

Fixes #468 

# Description

add keyboard arrows value changing

# Testing

open order widget/modal
click in price/quantity/trigger price field
click on keyboard up/down keys

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2022-12-06 12:57 UTC, sbelashevskiy requested changes

2022-12-06 12:57 UTC, sbelashevskiy commented on src/app/shared/directives/numerical.directive.ts
> +  @Input() atsNumerical: string | number | boolean = 1;
плохое название - не отражает сути этого поля. Если сюда передается степ, то почему это поле не назвать step?

2022-12-06 12:57 UTC, sbelashevskiy commented on src/app/shared/directives/numerical.directive.ts
> +
зачем здесь boolean?

2022-12-07 05:29 UTC, sbelashevskiy commented on src/app/shared/directives/numerical.directive.ts
> +  @Input() atsNumerical: string | number | boolean = 1;
не должно https://angular.io/guide/attribute-directives#binding-to-a-second-property

2022-12-07 05:36 UTC, sbelashevskiy commented on src/app/shared/directives/numerical.directive.ts
> +
Я добавил так и никаких предупреждений нет 
![image](https://user-images.githubusercontent.com/29191749/206097218-88325478-b086-4a4c-ab28-5c19a725fcc1.png)
![image](https://user-images.githubusercontent.com/29191749/206097231-b46a3d6e-8d57-4055-8d87-f3f4dbb082f8.png)

2022-12-07 08:15 UTC, agushasok commented on src/app/shared/directives/numerical.directive.ts
> +  @Input() atsNumerical: string | number | boolean = 1;
да. Просто хотел сделать без лишних инпутов, щас добавлю

2022-12-07 10:36 UTC, sbelashevskiy requested changes
Стрелками можно ввести отрицательно значение. С клавиатуры только положительные
![image](https://user-images.githubusercontent.com/29191749/206156584-8586c295-afa2-4771-b197-1bfe02bbf941.png)

2022-12-08 04:05 UTC, sbelashevskiy approved these changes

2022-12-08 04:05 UTC, merged