add internationalization
alor-broker/Astras-Trading-UI pull request #744
Opened 2022-12-21 11:54 UTC by agushasok

Fixes #729 

# Description

add internationalization

# Testing

go to terminal settings
go to general tab
switch language

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2022-12-22 09:26 UTC, sbelashevskiy requested changes
TechChart не переведен. Нужно в конфигурации проставить локаль
![image](https://user-images.githubusercontent.com/29191749/209092347-c165066e-f5ba-4ced-a893-d8c2103a2cb0.png)

![image](https://user-images.githubusercontent.com/29191749/209096574-756581b6-356a-4577-9f0b-4b3512570635.png)
С заглавной буквы
![image](https://user-images.githubusercontent.com/29191749/209096785-5859d035-2611-4e35-92fa-93919ebce6fb.png)
![image](https://user-images.githubusercontent.com/29191749/209097116-4ad0f6a1-ba9a-46c8-aa0c-57ba39246b13.png)
![image](https://user-images.githubusercontent.com/29191749/209097653-89541066-b951-4a44-afe1-78a892cb52ca.png)
![image](https://user-images.githubusercontent.com/29191749/209097868-057fc316-3caf-41dd-bfc1-b2aae6520351.png)
Скальперский стакан
![image](https://user-images.githubusercontent.com/29191749/209098169-33ec65af-ea9d-4d3e-8411-979d37e79c95.png)
![image](https://user-images.githubusercontent.com/29191749/209098315-c1c3abdd-1862-46b2-9a75-f82704ce904c.png)
![image](https://user-images.githubusercontent.com/29191749/209098543-5beb2d13-527a-4c36-a6d9-cb3d15a3bf4d.png)

![image](https://user-images.githubusercontent.com/29191749/209099315-fd1c4f44-ae32-4fe2-8940-e2493e043722.png)
![image](https://user-images.githubusercontent.com/29191749/209102050-605e23c0-fc6d-444b-83c0-33adb2a5e2af.png)

Все сделки
![image](https://user-images.githubusercontent.com/29191749/209100026-073ffad4-128d-4d39-be5e-6627912f51fd.png)
С заглавной
![image](https://user-images.githubusercontent.com/29191749/209100477-867f71f5-1b67-4c28-abeb-05bcd7fdda11.png)
![image](https://user-images.githubusercontent.com/29191749/209101151-77db8eb8-8449-4992-a759-36b4e30ecdfa.png)
![image](https://user-images.githubusercontent.com/29191749/209101317-b616a5b8-305c-4edf-9039-ec0f10ffdadc.png)

![image](https://user-images.githubusercontent.com/29191749/209101679-34bed2e8-e77e-416d-bb26-960f49cc9a00.png)

2022-12-22 12:49 UTC, agushasok commented on src/app/modules/all-instruments/components/all-instruments-settings/all-instruments-settings.component.html
> +      <nz-form-item class="compact" *transloco="let tSettings; scope: 'all-instruments/all-instruments-settings'">
без указания scope не подгружаются файлы из вложенных папок
<img width="354" alt="image" src="https://user-images.githubusercontent.com/45139991/209137679-374d5a5c-8021-4af1-a9e5-6454caf8d83f.png">

можно, развве что, в провайдеры мдулей/компонентов добавлять провайдер скоупа, но это, по сути, то же самое, что и сейчас

2022-12-22 12:54 UTC, agushasok commented on package.json
> +    "@ngneat/transloco": "4.1.1",
потому что её 12 дней назад выпустили

2022-12-23 04:36 UTC, sbelashevskiy commented on src/app/modules/all-instruments/components/all-instruments-settings/all-instruments-settings.component.html
> +      <nz-form-item class="compact" *transloco="let tSettings; scope: 'all-instruments/all-instruments-settings'">
Какая-то стремная либа - документации практически нет, все примеры по типу hello world. Элементарные вещи сделаны очень странно - фактически нужно мануально вызывать загрузку фалов и только потом его использовать. И хотя уже явно указан scope, все равно нужно писать полные пути, котрые по сути итак содержат scope

Лучше бы написать свою директиву, которая использует эту либу, но чтобы не нужно было scope явно указывать, а определять его из пути - как я для сервиса  описывал и утилиты составления ключей

2022-12-23 05:57 UTC, sbelashevskiy commented on src/app/modules/all-instruments/components/all-instruments-settings/all-instruments-settings.component.html
> +      <nz-form-item class="compact" *transloco="let tSettings; scope: 'all-instruments/all-instruments-settings'">
либо добавить провайдеры скоупа в компоненты и использовать эйлиасы

2022-12-23 12:57 UTC, sbelashevskiy approved these changes

2022-12-23 12:58 UTC, merged