update angular and ng-zorro to 15 version
alor-broker/Astras-Trading-UI pull request #771
Opened 2023-01-16 11:00 UTC by agushasok

Fixes #766  

# Description

update angular and ng-zorro to 15 version

# Testing

run yarn install

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2023-01-16 12:03 UTC, sbelashevskiy requested changes
Нужно обновить ВСЕ зависимости - в package.json остались зависимости, которые ориентированы на 14 ангуляр

2023-01-16 12:03 UTC, sbelashevskiy commented on src/app/modules/orderbook/components/scalper-order-book/scalper-order-book.component.ts
> +              <CdkVirtualScrollViewport | null | undefined>this.table?.cdkVirtualScrollViewport,
Зачем приводить типы здесь, когда их можно поправить в хелпере?

2023-01-16 12:44 UTC, sbelashevskiy requested changes
тесты упали
![image](https://user-images.githubusercontent.com/29191749/212681185-bd2a1dd7-48d5-4e17-b5fb-f985d2b9650d.png)

2023-01-16 12:51 UTC, agushasok commented
> тесты упали ![image](https://user-images.githubusercontent.com/29191749/212681185-bd2a1dd7-48d5-4e17-b5fb-f985d2b9650d.png)

хмм, локально всё ок

2023-01-17 04:39 UTC, sbelashevskiy approved these changes

2023-01-17 04:39 UTC, merged