add counter order hotkey
alor-broker/Astras-Trading-UI pull request #813
Opened 2023-02-03 11:50 UTC by agushasok

Fixes #562, #812 

# Description

add counter order hotkey

# Testing

open scalper orderbook
try to place orders holding alt button
quantity should be equal to position quantity volume

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2023-02-03 12:27 UTC, sbelashevskiy requested changes

2023-02-03 12:27 UTC, sbelashevskiy commented on src/app/shared/services/hot-key-command.service.ts
> +    merge(
что мешает это сделать в одном стриме с startWith?
Тут намешано:
1. Вечный BehaviorSubject, у которого нет вызова complete, а значит внутри него всегда живет subscribe
2. Subscribe , без unsubscribe

2023-02-03 12:27 UTC, sbelashevskiy commented on src/app/modules/orderbook/components/scalper-order-book/scalper-order-book.component.ts
>    private callWithWorkingVolume(action: (workingVolume: number) => void) {
нужно переимновать. Название метода четко указывает, что работаем с рабосим объемом, а внути неожиданно оказывается, что нет

2023-02-03 12:27 UTC, sbelashevskiy commented on src/app/modules/orderbook/components/scalper-order-book/scalper-order-book.component.ts
> +  private getPositionsCount(): Observable<number | undefined> {
в поле orderBookContext.orderBookPosition уже есть данные о текущей позиции, которые отображаются в стакане. Дополнительный вызов может привести к тому, что отображается одно, в выполнилось другое

2023-02-03 12:27 UTC, sbelashevskiy commented on src/app/modules/orderbook/services/scalper-orders.service.ts
> +  private getPositionsByPortfolio(instrumentKey: InstrumentKey, portfolio: PortfolioKey): Observable<Position | null> {
Не вижу смысла увеличивать длину имен методов. Позиции всегда привязаны к порифелю

2023-02-03 12:30 UTC, sbelashevskiy commented on src/app/shared/services/hot-key-command.service.ts
> +        map((e: KeyboardEvent) => ({
При нажатии shift при вводе в какой-либо input будет мелькать индикатор в стакане

2023-02-03 12:37 UTC, sbelashevskiy requested changes
Индикатор показывается 1 раз из 10

2023-02-03 14:39 UTC, agushasok commented on src/app/shared/services/hot-key-command.service.ts
> +    merge(
При подписке на стрим значение не будет эмититься сразу, а только при возникновении следующего события с уже новыми данными. (нажали alt, кликнули на строку, произошла подписка на стрим, отпустили alt, заэмитилось первое значение в подписке, где altKey уже false)

2023-02-03 14:41 UTC, agushasok commented on src/app/modules/orderbook/components/scalper-order-book/scalper-order-book.component.ts
> +  private getPositionsCount(): Observable<number | undefined> {
то же самое, что и со стримом модификаторов: значение заэмитится первый раз только при следующем событии после подписки

2023-02-06 04:11 UTC, sbelashevskiy commented on src/app/modules/orderbook/components/scalper-order-book/scalper-order-book.component.ts
> +  private getPositionsCount(): Observable<number | undefined> {
дак добавь в getPositionStateStream shareReplay({bufferSize: 1, refCount: true})

2023-02-06 04:12 UTC, sbelashevskiy commented on src/app/shared/services/hot-key-command.service.ts
> +    merge(
Дак добавь в стрим shareReplay(1)

2023-02-07 04:28 UTC, sbelashevskiy requested changes

2023-02-07 04:28 UTC, sbelashevskiy commented on src/app/modules/orderbook/components/scalper-order-book/scalper-order-book.component.ts
> +  positionState$!: Observable<ScalperOrderBookPositionState | null>;
зачем добавлять это поле??? Чем не устраивает поле orderBookContext.orderBookPosition$
Зачем использовать метод getPositionStateStream, который возвращал состояние для отображения. Причем это "тяжелый" стрим, который делает еще итерации по orderbook.
getOrderBookPositionStream возвращает позицию без всякой агрегации и его значение хранится в orderBookContext.orderBookPosition$

2023-02-07 04:28 UTC, sbelashevskiy commented on src/app/shared/services/hot-key-command.service.ts
> +        filter(() => !this.document.querySelector('input:focus')),
Это фиксит только input. на textaria индикатор мелькает

2023-02-08 04:05 UTC, sbelashevskiy approved these changes

2023-02-08 04:05 UTC, merged