Dm dev 751
alor-broker/Astras-Trading-UI pull request #862
Opened 2023-03-07 08:58 UTC by agushasok

Fixes #751 

# Description

add mobile version for app

# Testing

open app on mobile

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2023-03-07 10:38 UTC, agushasok commented on src/app/modules/light-chart/components/light-chart/light-chart.component.ts
> +          mobileDashboardTab: mt
потому что либа графика не может найти дивак с айдишником, когда выбран другой таб. А инициализация компонента происходит 1 раз на старе приложения. Он не находит айдишник и сыпит ошибки, и график, соответственно, не отрисовывает

2023-03-07 12:31 UTC, sbelashevskiy commented on src/app/modules/light-chart/components/light-chart/light-chart.component.ts
> +          mobileDashboardTab: mt
Почему такого не происходит на десктопном приложении?
Там вообще div с графиком не отрисовывается пока не добавлен виджет или пока виджет переключен в режим настройки.

Нужно найти нормальное решение

2023-03-10 10:08 UTC, agushasok commented on src/app/modules/light-chart/components/light-chart/light-chart.component.ts
> +          mobileDashboardTab: mt
Потому что при переключении на настройки компонент графика дестроится, так как на контейнер с компонентом ngif навешен, а потом при сохранении/отмене настроек, ngif переключается обратно и срабатывает ngOnInit

2023-03-10 10:10 UTC, agushasok commented on src/app/modules/light-chart/components/light-chart/light-chart.component.ts
> +          mobileDashboardTab: mt
Можно сделать, чтоб виджеты прогружались не при старте приложения, а при переключении на таб, и дестроились при переключении на другой, но в таком случае они будут каждый раз сбрасываться при переключении. Такой вариант устроит?

2023-03-10 10:15 UTC, agushasok commented on src/app/modules/dashboard/components/mobile-navbar/mobile-navbar.component.ts
> +  selectedPortfolio$!: Observable<PortfolioExtended | null>;
оно в шаблоне используется

2023-03-10 10:59 UTC, sbelashevskiy commented on src/app/modules/light-chart/components/light-chart/light-chart.component.ts
> +          mobileDashboardTab: mt
Либа не находит div, потому уничтожается содержимое таба, когда он становится неактивным. У тебя вообще при переключении каждый виджет отрисовывается заново. Насколько я помню, обсуждалось, что виджеты не должны перерисовываться. Для сравнения посмотри на блоттер - при переключении содержимое табов не дропается

2023-03-10 12:36 UTC, agushasok commented on src/app/modules/order-submit/components/order-submit/order-submit.component.spec.ts
> +    dashboardContextServiceSpy = jasmine.createSpyObj('DashboardContextService', ['selectedPortfolio$, selectedDashboard$']);
он используется в сторе, и без его объявления здесь тест крашится

2023-03-10 13:09 UTC, sbelashevskiy requested changes

2023-03-10 13:09 UTC, sbelashevskiy commented on src/app/shared/components/instrument-search/instrument-search.component.ts
> +  searchControl = new FormControl();
Зачем тут использовать FormControl?
Он вне формы, на нем нет никакой валидации.

2023-03-10 13:09 UTC, sbelashevskiy commented on src/app/store/mobile-dashboard/mobile-dashboard.effects.ts
> +  private excludeWidgetSettings(widget: Widget) {
каждый виджет должен сам знать какие сеттинги в какой версии показывать. 
Виджеты являются расширениями. Ядро вообще не должно знать какие виджеты в нем есть

2023-03-10 13:14 UTC, agushasok commented on src/app/shared/components/instrument-search/instrument-search.component.ts
> +  searchControl = new FormControl();
потому что поле поиска не обнуляется при очистке контрола в компонентах, где этот компонент используется

2023-03-10 14:12 UTC, agushasok commented on src/app/store/mobile-dashboard/mobile-dashboard.effects.ts
> +  private excludeWidgetSettings(widget: Widget) {
это значит, что в компоненте настроек каждого виджета надо проверять, мобильная версия открыта или десктопная

2023-03-13 06:39 UTC, sbelashevskiy commented on src/app/shared/components/instrument-search/instrument-search.component.ts
> +  searchControl = new FormControl();
Дак надо выяснить в чем причина, а не втыкать таки вот костыли. Теперь значение хранится отдельно, а параллельно существует еще контрол со значением тоьлко ради того, что нужно очистить значение. Нужно посмотреть что приходит при очистке родительской формы - на ngModel все должно работать

2023-03-13 06:49 UTC, sbelashevskiy requested changes

2023-03-13 06:49 UTC, sbelashevskiy commented on src/app/store/mobile-dashboard/mobile-dashboard.effects.ts
> +  private excludeWidgetSettings(widget: Widget) {
а при таком подходе при добавлении нового виджета нужно залазить в core и менять его. Это противоречит принципам SOLID. Виджеты должны быть максимально независимы друг от друга и  core не должен подстраиваться по них и вообще знать какие-либо их особенности.

Более того в настройках виджета появляется непонятное поле excludedFields, которое **самому виджету никак не нужно** и  используется исключительно компонетом настроек виджета. При этом место в locaStorage занимает

2023-03-13 09:34 UTC, sbelashevskiy approved these changes

2023-03-13 09:35 UTC, merged