add treemap widget
alor-broker/Astras-Trading-UI pull request #877
Opened 2023-03-17 12:06 UTC by agushasok

Fixes #872 

# Description

added treemap widget

# Testing

add treemap widget

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2023-03-17 12:54 UTC, sbelashevskiy requested changes

2023-03-17 12:54 UTC, sbelashevskiy commented on src/app/app.module.ts
> +import 'chartjs-chart-treemap';
Что это за странный импорт, который не используется в модуле и почему он находится в App.module, а не модуле виджета?
Кроме того, судя по всему все работает и без этого импорта

2023-03-17 12:54 UTC, sbelashevskiy commented on src/app/modules/treemap/components/treemap/treemap.component.ts
> +  @Input() guid!: string;
если утверждается что инпут всегда будет иметь значение, то его нужно внести в селектор компонента, как это сделано для других виджетов

2023-03-17 12:54 UTC, sbelashevskiy commented on src/app/modules/treemap/components/treemap/treemap.component.ts
> +  selectedSector$ = new BehaviorSubject('');
BehaviorSubject должен быть закомплитен в onDesctroy

2023-03-17 12:54 UTC, sbelashevskiy commented on src/app/modules/treemap/components/treemap/treemap.component.ts
> +  isCursorOnSector$ = new BehaviorSubject(false);
BehaviorSubject должен быть закомплитен в onDesctroy

2023-03-17 12:54 UTC, sbelashevskiy commented on src/app/modules/treemap/components/treemap/treemap.component.ts
> +  ctx!: CanvasRenderingContext2D;
только для переменных, инициализируемых в onInit можно утверждать, что они всегда имеют значение. Эта переменная иниуциализируется в ngAfterViewInit, а значит может быть undefined. Тем более она определяется в observable

2023-03-17 12:54 UTC, sbelashevskiy commented on src/app/modules/treemap/components/treemap/treemap.component.ts
> +        mapWith(
зачем тут mapWith, а не combineLatest? selectedSelector никак не зависит от getTreemap

2023-03-17 12:54 UTC, sbelashevskiy commented on src/app/modules/treemap/components/treemap/treemap.component.ts
> +          .map(t => ({
зачем сначала по куче данных делать маппинг, а только потом их фильтровать?

2023-03-17 12:54 UTC, sbelashevskiy commented on src/app/modules/treemap/components/treemap/treemap.component.ts
> +        mapWith(
почему чтение темы стоит после чтения данных? Тема меняется гораздо реже и перечитывать ее с данными нет никакого смысла.
Ну тот же вопрос, что и для this.selectedSector$: зачем тут mapWith, если этот стрим от предыдущих никак не зависит

2023-03-17 12:54 UTC, sbelashevskiy commented on src/app/modules/treemap/components/treemap/treemap.component.ts
> +        this.chart?.clear();
При объявлении переменной chart утверждается, что она всегда инициализирована, а тут она проверяется на unbdefined

2023-03-17 12:54 UTC, sbelashevskiy commented on src/app/modules/treemap/components/treemap/treemap.component.ts
> +                if (this.selectedSector$.getValue()) {
Прекращай так делать с observable - чтение значения через geValue это костыль. Значение из observable должно быть считано через pipe(take(1)). Тогда не придется втыкакть setTimeout

2023-03-17 12:54 UTC, sbelashevskiy commented on src/app/modules/treemap/components/treemap/treemap.component.ts
> +  private getTooltipLabel = (tooltipItem: any): any => {
в либе tooltipItem типизировано.
Фтн должно использоваться только в крайнем случае, когда тип переменной/аргумента неизвестен

2023-03-17 12:54 UTC, sbelashevskiy commented on src/app/modules/treemap/components/treemap/treemap.component.ts
> +      .subscribe(data => {
take(1)

2023-03-17 12:54 UTC, sbelashevskiy commented on src/app/modules/treemap/components/treemap/treemap.component.ts
> +        mapWith(
MapWith должно использолваться только для связанных стримов, когда значение одного определятся другое. Тут вообще можно использовать withLatestFrom для this.translatorService.getTranslator

2023-03-17 12:54 UTC, sbelashevskiy commented on src/app/modules/treemap/services/treemap.service.ts
> +      }
нет обработки ошибок

2023-03-17 12:54 UTC, sbelashevskiy commented on src/app/modules/treemap/widgets/treemap-widget/treemap-widget.component.ts
> +    WidgetSettingsCreationHelper.createWidgetSettingsIfMissing<NewsSettings>(
Причем тут NewsSettings?

2023-03-17 12:54 UTC, sbelashevskiy commented on src/app/shared/services/theme.service.ts
> +    treemapBackground: '#1F2530'
переменная темы не должны привязываться к конкретному виджету, т.к. может быть переиспользована еще где-то

2023-03-17 12:54 UTC, sbelashevskiy commented on src/assets/i18n/en.json
> +    "TreemapSettings": "Market map"
Map - с большой буквы, также, как другие имена виджетов

2023-03-17 13:14 UTC, agushasok commented on src/app/modules/treemap/components/treemap/treemap.component.ts
> +  private getTooltipLabel = (tooltipItem: any): any => {
он не определяет поля, которые там присутствуют

2023-03-20 04:55 UTC, sbelashevskiy requested changes

2023-03-20 04:55 UTC, sbelashevskiy commented on src/app/modules/treemap/components/treemap/treemap.component.ts
> +  @Input() guid!: string;
Я не вижу никаких исправлений - на поле все еще висит !, в селектор это поле не добавлено

2023-03-20 04:55 UTC, sbelashevskiy commented on src/app/modules/treemap/components/treemap/treemap.component.ts
> +  private getTooltipLabel = (tooltipItem: any): any => {
Тип этого метода определяется типом label 
![image](https://user-images.githubusercontent.com/29191749/226248305-dde944ae-58a2-4ab7-83c0-371892b8ff64.png)
![image](https://user-images.githubusercontent.com/29191749/226248407-feab330e-65e0-4a6a-bc21-b15808db674f.png)

2023-03-20 04:55 UTC, sbelashevskiy commented on src/app/modules/treemap/models/treemap.model.ts
> +export const averageTileSize = 4000;
зачем эти константы в модели. Их только 1 компонент использует

2023-03-20 11:17 UTC, sbelashevskiy approved these changes

2023-03-20 11:17 UTC, merged