fix prices view in treemap tooltips
alor-broker/Astras-Trading-UI pull request #895
Opened 2023-04-03 11:36 UTC by agushasok

Fixes #886 

# Description

fix prices view in treemap tooltips
add instrument select on click in treemap

# Testing

open market map widget
hover on instruments
click on instruments

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2023-04-04 04:36 UTC, sbelashevskiy requested changes

2023-04-04 04:36 UTC, sbelashevskiy commented on src/app/shared/utils/math-helper.ts
> +  static getBaseNumber(value: number | null | undefined, allowRounding = false, roundPrecision = 2) {
Почему getBaseNumber, когда возвращается форматированное значение?
BaseNumber это база 1000, 1000000... по которой идет сокращение.
И нужно прописылвать возвращаемое значени у метода

2023-04-04 04:36 UTC, sbelashevskiy commented on src/assets/i18n/shared/short-number/ru.json
> +    "long": "трлн"
в русском языке сокращения должны заканчиваться точкой

2023-04-04 04:36 UTC, sbelashevskiy commented on src/assets/i18n/shared/short-number/en.json
> +    "long": "tln"
Ты проверял эти сокращения? Не нахожу чтобы триллионы сокращались как tln
https://wordeng.com/abbreviations/trillion
https://www.allacronyms.com/trillion/abbreviated

2023-04-04 04:36 UTC, sbelashevskiy commented on src/app/shared/utils/math-helper.ts
1. Эту логику нужно вынести в отдельный файл.
2. На нее нужно написать тесты, как это было сделано на pipe. Только по этим тестам была понятна логика работы флага allowRounding

2023-04-04 04:36 UTC, sbelashevskiy commented on src/app/shared/utils/math-helper.ts
> +export interface FormatToBase {
Имя интрефейса - глагол. Должно быть существительное, что-то типа ShortValue

2023-04-04 04:36 UTC, sbelashevskiy commented on src/app/shared/utils/math-helper.ts
> +    if (!value && value !== 0) {
т.е 0 вообще никогда не отобразится? Почему, это такое же число

2023-04-04 07:09 UTC, agushasok commented on src/assets/i18n/shared/short-number/en.json
> +    "long": "tln"
https://www.antidote.info/en/blog/reports/millions-billions-and-other-large-numbers

да, я тут смотрел

2023-04-04 07:15 UTC, agushasok commented on src/app/shared/utils/math-helper.ts
> +    if (!value && value !== 0) {
нет, он наоборот пропускает 0 дальше в методе и потом просто его вернёт

2023-04-04 07:42 UTC, sbelashevskiy commented on src/app/shared/utils/math-helper.ts
> +    if (!value && value !== 0) {
Где он пропускает?
Он вернет null и в компоненте ничего не отобразится
![image](https://user-images.githubusercontent.com/29191749/229722660-13dd562e-edf1-4843-8f36-0f0efab76d85.png)

2023-04-04 07:47 UTC, sbelashevskiy commented on src/app/shared/utils/math-helper.ts
> +    if (!value && value !== 0) {
На null || undefined можно проверить value != null

2023-04-04 10:03 UTC, agushasok commented on src/assets/i18n/shared/short-number/ru.json
> +    "long": "трлн"
только для тысяч - да, для остальных - нет

2023-04-05 03:59 UTC, sbelashevskiy approved these changes

2023-04-05 04:00 UTC, merged