add push notifications with firebase
alor-broker/Astras-Trading-UI pull request #917
Opened 2023-04-14 07:19 UTC by agushasok

Fixes #910

# Description

add push notifications with firebase

# Testing

open app
crate order
look click on bell icon

close or unfocus browser window
create order on another device
look at the push notifications

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2023-04-14 08:39 UTC, sbelashevskiy requested changes
1. Для уведомлений firebase нужно создать отдельный модуль, а не пихать его в дженериковый модуль notifications. См. как расположены другие провайдеры ApplicationReleaseNotificationProvider, FeedbackNotificationsProvider
2. Не надо в названиях модулей и сервисов использовать название конкретной технологии. Названия должны быть абстрактными типа PushNotificationsService

2023-04-14 08:39 UTC, sbelashevskiy commented on src/app/modules/notifications/services/firebase-notifications-provider.ts
1. Зачем делать инициализацию в конструкторе? Что мешает завести observable в переменной класса и если она не инициализирована, то инициализировать ее и вернуть. А если она уже инициализорована, то протсто ее вернуть. И все это сделать в методе getNotifications, тоько после того, как кнопка оповещений проинициализируется и запросит эти данные ,а не при инициализации приложения, что затормозит его прогрузку.
2. Вообще не понимаю смысл в двух переменных notificationsSubject и notifications$. Схема, когда данные приходят по 1 и их нужно накапливать и формировать из них массив уже реализована в приложении в нескольких местах, например PortfolioSubscriptionsService.getTradesSubscription

2023-04-14 08:39 UTC, sbelashevskiy commented on src/app/modules/notifications/services/firebase-notifications.service.ts
1. addToken должен быть observable с shareReplay. Он должен включаться в каждый метод, который обращается к серверу. Он должен храниться локально и в другие методы подставляться через метод (getToken) и инициализироваться 1 раз, а потому переиспользоваться.
2. Не должно быть никакого init, где идет подписка на уведомления. Подписку на уведомления должен инициировать соответствующий провайдер уведомлений или явное действие пользователя

2023-04-14 08:39 UTC, sbelashevskiy commented on src/environments/environment.dev.ts
приватные данные  типа apiKey, appId нужно устанавливать через CI. Ну и теперь их нужно менять т.к. теперь их все знают

2023-04-14 08:39 UTC, sbelashevskiy commented on src/firebase-messaging-sw.js
В этом файле продублирована информация из environment. Нужно искать решение как этого избежать

2023-04-14 08:39 UTC, sbelashevskiy commented on src/app/modules/application-meta/application-meta.module.ts
> +    { provide: NOTIFICATIONS_PROVIDER, useClass: FirebaseNotificationsProvider, multi: true },
Зачем тут этот провайдер? Он никак не относится к этому модулю
Нужно создать свой модуль для этой фичи или прописать провайдер в shared модуле, как это сделано для FeedbackNotificationsProvider

2023-04-18 04:30 UTC, sbelashevskiy requested changes

2023-04-18 04:30 UTC, sbelashevskiy commented on src/app/modules/notifications/models/firebase-notifications.model.ts
этот файл нужно перенести в соответствующий модуль

2023-04-18 10:19 UTC, agushasok commented on src/firebase-messaging-sw.js
<img width="716" alt="image" src="https://user-images.githubusercontent.com/45139991/232747994-48fc7d88-1db7-4035-bbb6-ac3854b525f3.png">

2023-04-18 10:22 UTC, agushasok commented on src/environments/environment.dev.ts
<img width="871" alt="image" src="https://user-images.githubusercontent.com/45139991/232748730-5d9470c4-8990-4c14-8d40-a331b77c906f.png">

2023-04-19 05:39 UTC, sbelashevskiy approved these changes

2023-04-19 05:39 UTC, merged