Dm dev 934
alor-broker/Astras-Trading-UI pull request #959
Opened 2023-05-15 10:06 UTC by agushasok

Fixes #934 

# Description

add arbitrations extension widget

# Testing

add arbitrations extension widget on board

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2023-05-16 15:30 UTC, PilgrimViis commented on src/app/modules/arbitration-extension/components/arbitration-extension-manage/arbitration-extension-manage.component.html
> +        <nz-form-label>{{t('arbitrationExtensionArbitrationExtensionManage.portfolioLabel')}}</nz-form-label>
Переименуй в коде тоже этот extension

2023-05-17 05:12 UTC, sbelashevskiy requested changes
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/1c707d61-70ef-4380-842c-25420c36f85b)
Форма не соответствует общему стилю форм в приложении. У нас labels либо сверху контролов, либо слева и контролы выравнены друг относительно друга
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/7ce88f32-70be-4add-8cdf-7a02ba5790ae)
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/ee06a5c8-d703-47a0-b408-4e631f36db9b)
такого стиля и нужно придерживаться

2023-05-17 05:12 UTC, sbelashevskiy commented on src/app/modules/arbitration-extension/components/arbitration-extension-manage/arbitration-extension-manage.component.ts
> +      quantity: new UntypedFormControl(null, Validators.required),
Где валидаторы min/max на все number поля?

2023-05-17 05:12 UTC, sbelashevskiy commented on src/app/modules/arbitration-extension/components/arbitration-extension-manage/arbitration-extension-manage.component.html
вывода ошибок ни у одного поля нет. Даже required. Как пользователь должен догадаться в чем проблема?

2023-05-17 05:17 UTC, sbelashevskiy requested changes

2023-05-17 05:17 UTC, sbelashevskiy commented on src/app/modules/arbitration-extension/components/arbitration-extension-manage/arbitration-extension-manage.component.ts
> +    this.form.valueChanges.subscribe(value => {
TAKEUNTIL

2023-05-17 05:17 UTC, sbelashevskiy commented on src/app/modules/arbitration-extension/components/arbitration-extension-manage/arbitration-extension-manage.component.ts
> +  form = new UntypedFormGroup({
Если форма объявляется так, то нужно использовать типизированную форму. Untyped формы можно использовать только при создании формы динамически, когда она имее сложный тип

2023-05-17 05:23 UTC, sbelashevskiy requested changes
Сужение виджета не обрабатывается вообще
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/116ee32b-86eb-49ba-b04e-71964e27ea56)
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/3460646e-82b1-4bb7-ab02-e0e9b6f8dfb6)
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/6da65317-1383-4e4c-ae28-b36b6de1cb42)


Кнопка ADD теряется среди остальных. Вообще не очевидно, что это кнопка в заголовке и ее смысл не понятен. И начертания у нее точно такие же, как у кнопки закрытия виджета, кнопки удаления строки. Даже тултипа нет никакого
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/5c670842-85cf-4e7e-ba51-14c064200cba)

2023-05-17 14:34 UTC, PilgrimViis commented
> ![image](https://user-images.githubusercontent.com/29191749/238839689-1c707d61-70ef-4380-842c-25420c36f85b.png) Форма не соответствует общему стилю форм в приложении. У нас labels либо сверху контролов, либо слева и контролы выравнены друг относительно друга ![image](https://user-images.githubusercontent.com/29191749/238839950-7ce88f32-70be-4add-8cdf-7a02ba5790ae.png) ![image](https://user-images.githubusercontent.com/29191749/238839999-ee06a5c8-d703-47a0-b408-4e631f36db9b.png) такого стиля и нужно придерживаться

Вот +1 на это. Тоже глаз зацепился, но я не смог понять что не так.

2023-05-19 09:04 UTC, sbelashevskiy requested changes
1. не отмечены красно звездочкой required поля
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/56e2d9a9-d48b-438e-82fb-c93b91fde9cd)
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/9504ff5c-176d-4cc2-999b-15d75e8bb44e)


2. Hover стиль кнопок отличается от стандартного. Вообще для кнопок Buy/Sell есть специальный миксин buySellButton

3. Окно add/edit закрывается при клике вне его. Окна на создание / редактирование заявки так не закрываются и явно имею кнопку calncel. Пользователь модет ввести данные и из-за случайного клика все стереть. Нужно делать одно поведение, один стиль

2023-05-19 09:04 UTC, sbelashevskiy commented on src/app/modules/arbitrage-spread/services/arbitrage-spread.service.ts
> +  buySpread(spread: ArbitrageSpread, volume = 1, isReverseBuy = false) {
Зачем тут isReverseBuy?
Почему нельзя назвать метод submitSpreadOrder и явно передавать Side?

2023-05-19 11:09 UTC, agushasok commented on src/app/modules/arbitrage-spread/services/arbitrage-spread.service.ts
> +  buySpread(spread: ArbitrageSpread, volume = 1, isReverseBuy = false) {
Потому что там выставляется две заявки: одна на покупку, другая на продажу

2023-05-19 11:09 UTC, agushasok commented on src/app/modules/arbitrage-spread/components/arbitrage-spread-manage/arbitrage-spread-manage.component.ts
> +    this.formChangeSub = this.form.valueChanges.subscribe(value => {
там отписка в дестрое есть

2023-05-19 11:10 UTC, agushasok commented on src/app/modules/arbitrage-spread/components/arbitrage-spread-manage/arbitrage-spread-manage.component.html
> +  <div class="d-flex flex-direction-column" [formGroup]="firstLegFormGroup">
да ё-моё...какая-то привычка писать именно так...

2023-05-22 04:37 UTC, sbelashevskiy requested changes
Форма и стили кнопок не исправлены

2023-05-22 04:37 UTC, sbelashevskiy commented on src/app/modules/arbitrage-spread/services/arbitrage-spread.service.ts
> +  buySpread(spread: ArbitrageSpread, volume = 1, isReverseBuy = false) {
Дак у тебя в вызывающем явно прописано:
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/fdf4b0a9-f7fc-4bf0-8b41-adca8179fc27)

![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/c9a77c9b-5bcb-4db4-b807-dfb116915a96)

Методы называются Buy/Sell, кнопки на UI Buy/Sell, а метод в сервисе buy.. c каким-то непонятным флагом.

Что мешает просто передать side для заявки в сервис и при side=Buy первую заявку выставлять Sell, вторую Buy если это такая логика покупки/продажи. Это в разы читабельнее и понятнее, чем в вызывающем коде догадываться что же делает этот флаг

2023-05-22 09:43 UTC, sbelashevskiy requested changes
Если выбран портфель и поменять инструмент, то есть возможность выбрать инструмент с одной биржи, а портфель  с другой
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/5a9f8156-d6e9-4e7b-bee1-21a78dfc6fe2)

2023-05-22 10:15 UTC, sbelashevskiy approved these changes

2023-05-22 10:15 UTC, merged