add linked orders
alor-broker/Astras-Trading-UI pull request #983
Opened 2023-05-25 15:50 UTC by agushasok

Fixes #969 

# Description

init linked orders logic

# Testing

see in linked issue 

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

2023-05-26 04:24 UTC, sbelashevskiy requested changes
1. Поле цены может быть отрицательным
2. ВСЕ числовые поля должны быть ограничены максимальным значением т.к бэк просто нее примет слишком большие числа
3. На тестовом аккаунте для всех стоп заявок открывается пустое окно
![image](https://github.com/alor-broker/Astras-Trading-UI/assets/29191749/dd460cb0-127b-4ddd-9fae-301edcdc24c1)

2023-05-26 04:24 UTC, sbelashevskiy commented on src/app/shared/models/orders/orders-group.model.ts
> +export interface OrdersGroupRes {
Зачем тут два набора практически одинаковых моделей отличающихся регистром и переименованным 1 полем? Зачем вообще переименовывать 1 поле в модели приложения, если от сервера оно приходит с другим именем?

Если с бэка приходит кривое форматирование, то нужно об этом сказать бэкендерам, чтобы правили. Это API не только для данного приложения и если один из методов нарушает правила общего форматирования респонзов, то нужно править этот метод

2023-05-26 04:24 UTC, sbelashevskiy commented on src/app/shared/services/orders/orders-group.service.ts
> +interface CreateOrderGroupReq {
этот интерфейс не экспортируется. Им невозможно воспользоваться вне этого файла. 
Данный интерфейс должен быть в моделях и должен быть доступен вне файла

2023-05-26 04:24 UTC, sbelashevskiy commented on src/assets/i18n/blotter/orders/en.json
> +  "exportToFile": "Export to file",
Зачем это копипастить во все компоненты, если это явно общие поля?

2023-05-29 13:04 UTC, sbelashevskiy requested changes
Открытие модалки  на мобильной версии подвешивает приложение на какое-то время. ТАкое ощущение, что виджет блоттера вообще перезагружается

2023-05-29 13:10 UTC, agushasok commented on src/app/modules/blotter/widgets/orders-group-modal-widget/orders-group-modal-widget.component.html
> +  nzWidth="600px"
для того, чтоб текст в группах не переносился. Без указания ширины, модалка узковата. В модалку помощи тоже ширина передаётся.

2023-05-30 04:35 UTC, sbelashevskiy commented on src/app/modules/blotter/components/orders-group-modal/orders-group-modal.component.ts
> +                  groupOrderMinPrice = (o as StopOrder).triggerPrice || o.price;
groupOrderMinPrice = Math.min(groupOrderMinPrice , (o as StopOrder).triggerPrice || o.price)
 и не нужно дважды делать приведение
 
 И так для остальных 3х случаев

2023-05-30 04:35 UTC, sbelashevskiy commented on src/app/modules/blotter/widgets/orders-group-modal-widget/orders-group-modal-widget.component.html
> +  nzWidth="600px"
Модалка помощи гораздо, гораздо шире и там это оправдано. Делать модалку шире чтобы вмещался текст так себе решение, что уже было несколько раз. Есть длинные тикеры, есть длинные цены. Нужно корректно обрабатывать  переренос

2023-05-30 04:36 UTC, sbelashevskiy reviewed
*

2023-05-30 09:38 UTC, sbelashevskiy approved these changes

2023-05-30 09:59 UTC, merged